# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from ChatbotGUI3 import ChatBotGUI
from TextingGUI3 import TextingGUI
import platform

if platform.system() == 'Windows':
    import mock_alsaaudio as alsaaudio
else:
    import alsaaudio
class VolumeControl:
    def __init__(self, mixer_name='Master'):
        self.mixer = alsaaudio.Mixer(mixer_name)

    def get_volume(self):
        return self.mixer.getvolume()[0]

    def set_volume(self, volume):
        if 0 <= volume <= 100:
            self.mixer.setvolume(volume)
        else:
            print("Giá trị âm lượng phải trong khoảng 0-100")

    def increase_volume(self, step=15):
        current_volume = self.get_volume()
        new_volume = min(100, current_volume + step)
        self.set_volume(new_volume)

    def decrease_volume(self, step=15):
        current_volume = self.get_volume()
        new_volume = max(0, current_volume - step)
        self.set_volume(new_volume)
class Ui_MainWindow(object):
    def __init__(self):
        super().__init__()
        self.volume_control = VolumeControl()
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 480)
        MainWindow.setMinimumSize(QtCore.QSize(720, 480))
        MainWindow.setMaximumSize(QtCore.QSize(720, 480))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.LB_Logo = QtWidgets.QLabel(self.centralwidget)
        self.LB_Logo.setGeometry(QtCore.QRect(0, 0, 720, 100))
        self.LB_Logo.setText("")
        self.LB_Logo.setPixmap(QtGui.QPixmap("/home/thang/document/Datasource/Hust_longLogo.jpg"))
        self.LB_Logo.setScaledContents(True)
        self.LB_Logo.setAlignment(QtCore.Qt.AlignCenter)
        self.LB_Logo.setObjectName("LB_Logo")
        self.BTN_Chatbot = QtWidgets.QPushButton(self.centralwidget)
        self.BTN_Chatbot.setGeometry(QtCore.QRect(150, 200, 130, 90))
        self.BTN_Chatbot.setObjectName("BTN_Chatbot")
        self.BTN_VolumeUp = QtWidgets.QPushButton(self.centralwidget)
        self.BTN_VolumeUp.setGeometry(QtCore.QRect(300, 100, 130, 90))
        self.BTN_VolumeUp.setObjectName("BTN_VolumeUp")
        self.BTN_Parents = QtWidgets.QPushButton(self.centralwidget)
        self.BTN_Parents.setGeometry(QtCore.QRect(450, 200, 130, 90))
        self.BTN_Parents.setObjectName("BTN_Parents")
        self.BTN_VolumeDown = QtWidgets.QPushButton(self.centralwidget)
        self.BTN_VolumeDown.setGeometry(QtCore.QRect(300, 300, 130, 90))
        self.BTN_VolumeDown.setObjectName("BTN_VolumeDown")
        self.BAR_Volume = QtWidgets.QProgressBar(self.centralwidget)
        self.BAR_Volume.setGeometry(QtCore.QRect(100, 110, 121, 23))
        self.BAR_Volume.setProperty("value", 24)
        self.BAR_Volume.setObjectName("BAR_Volume")
        self.LB_VolumeState = QtWidgets.QLabel(self.centralwidget)
        self.LB_VolumeState.setGeometry(QtCore.QRect(20, 110, 75, 20))
        self.LB_VolumeState.setObjectName("LB_VolumeState")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 720, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.BTN_VolumeUp.clicked.connect(self.VolumeUP)
        self.BTN_VolumeDown.clicked.connect(self.VolumeDOWN)
        self.BTN_Chatbot.clicked.connect(self.StartChatbotGUI)
        self.BTN_Parents.clicked.connect(self.StartTextingGUI)
        self.BAR_Volume.setValue(self.volume_control.get_volume())
        
        self.initallGUI()
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        #self.LB_Logo.setText(_translate("MainWindow", "TextLabel"))
        self.BTN_Chatbot.setText(_translate("MainWindow", "Chatbot"))
        self.BTN_VolumeUp.setText(_translate("MainWindow", "Tăng âm lượng"))
        self.BTN_Parents.setText(_translate("MainWindow", "Nói chuyện với \nbố mẹ"))
        self.BTN_VolumeDown.setText(_translate("MainWindow", "Giảm âm lượng"))
        self.LB_VolumeState.setText(_translate("MainWindow", "Âm lượng:"))

    def initallGUI(self):
        self.ChatbotWindow = QtWidgets.QMainWindow()
        self.Chatbotclass = ChatBotGUI()
        self.Chatbotclass.setupui(self.ChatbotWindow)
        self.TextingWindow = QtWidgets.QMainWindow()
        self.Textingclass = TextingGUI()
        self.Textingclass.setupUi(self.TextingWindow)
    def StartChatbotGUI(self):
        self.ChatbotWindow.show()
    def StartTextingGUI(self):
        self.TextingWindow.show()
    def VolumeUP(self):
        self.volume_control.increase_volume()
        self.BAR_Volume.setValue(self.volume_control.get_volume())
    def VolumeDOWN(self):
        self.volume_control.decrease_volume()
        self.BAR_Volume.setValue(self.volume_control.get_volume())
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
